---

- name: Apply Golden Config
  tags: ios
  when: ansible_network_os|lower == 'ios'
  ios_config:
    src: ios.j2


- name: Apply Golden Config - NXOS
  tags: nxos
  when: ansible_network_os|lower == 'nxos'
  nxos_config:
    src: nxos.j2
