---

#
# Roles to run on every instance
#
- name: common
  hosts: all
  tags: common
  connection: network_cli
  gather_facts: no
  vars:
    ansible_user: cisco
    ansible_ssh_pass: cisco
  pre_tasks:
    - ios_facts:
        gather_subset: all
      register: ios_facts
      when: ansible_network_os|lower == 'ios'

    - nxos_facts:
        gather_subset: all
      register: ios_facts
      when: ansible_network_os|lower == 'nxos'

  roles:
    # run cleanup as early as possible, since current roles may conflict
    # with old stuff
    - SNMP
    #- Console
