snmp_community_ro: public

snmp_community_rw: private

snmp_ro_acl: SNMP_RO_ACL
snmp_rw_acl: SNMP_RW_ACL

snmp_ro_acl_lines:
  - permit ip host 1.1.1.1 any
  - permit ip host 2.2.2.2 any
  - permit ip host 3.3.3.3 any

snmp_rw_acl_lines:
  - permit ip host 1.1.1.1 any
  - permit ip host 2.2.2.2 any
  - permit ip host 3.3.3.3 any
